# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=25)),
                ('var', models.CharField(max_length=10)),
                ('plot', models.CharField(choices=[('scatter', 'scatter'), ('bar', 'bar'), ('line', 'line')], default='scatter', max_length=10)),
            ],
        ),
    ]
