# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='var',
            field=models.CharField(max_length=25),
        ),
    ]
