# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20170221_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='fromdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='chart',
            name='todate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
