# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20170225_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='plot',
            field=models.CharField(choices=[('scatter', 'scatter'), ('line', 'line'), ('scatterline', 'scatterline')], default='scatter', max_length=15),
        ),
    ]
