# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=25)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('var', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surface', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=25)),
                ('obj', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=15)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
