# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0002_auto_20170130_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
