# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0003_capture_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='unity',
            new_name='unit',
        ),
    ]
