# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0004_auto_20170201_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='time',
        ),
        migrations.AddField(
            model_name='capture',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
